#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           rightMotor2,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           leftMotor2,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(2000);
	motor[rightMotor] = 32;
	wait1Msec(2000);
	motor[leftMotor] = 32;
	wait1Msec(2000);
	motor[rightMotor2] = 32;
	wait1Msec(2000);
	motor[leftMotor2] = 32;
	wait1Msec(2000);

	wait1Msec(2000);
	motor[rightMotor] = 0;
	wait1Msec(2000);
	motor[leftMotor] = 0;
	wait1Msec(2000);
	motor[rightMotor2] = 0;
	wait1Msec(2000);
	motor[leftMotor2] = 0;
	wait1Msec(2000);
}
