#pragma config(Sensor, in1,    powerE,         sensorAnalog)
#pragma config(Motor,  port2,           left1,         tmotorVex393, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           intake,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           driveLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           driveRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           up,            tmotorVex269, openLoop)
#pragma config(Motor,  port8,           right1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           right2,        tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true) // Displays Battery Level to LCD
	{
	wait1Msec(100);
	int powerExpanderBatteryV = SensorValue[in1]/.28;
	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDPos(0,0);
		displayNextLCDString("Cortex Bat:");
		displayNextLCDNumber(nAvgBatteryLevel);
	displayLCDPos(1,0);
		displayNextLCDString("PowerE Bat:");
		displayNextLCDNumber(powerExpanderBatteryV);
	}


}
