#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    powerE,         sensorAnalog)
#pragma config(Sensor, dgtl1,  ultrasonic,     sensorSONAR_cm)
#pragma config(Sensor, I2C_1, driveLeftEncoder ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2, driveRightEncoder ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3, shootRightEncoder ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4, shootLeftEncoder ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           up,            tmotorVex393, openLoop)
#pragma config(Motor,  port2,           left1,         tmotorVex393, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port3,           left2,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           driveLeft2,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           driveLeft,     tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port6,           driveRight,    tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port7,           driveRight2,   tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port8,           right1,        tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port9,           right2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          intake,        tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
////////////////////////////////////////////////////////////////////////////////////////

int a=35; // startup speed / slowdown speed
int deadzone=15; // Deadzone for joysticks
int b=43; // main shooting speed
float driveTrainSpeedControl = 1;
float shootercorr = 1.0; //Not used anymore
int sonarValue;

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.


	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	StopTask(usercontrol);
	motor[left1] =  a;
	motor[left2] = a;
	motor[right1] = a;
	motor[right2] = a;
	wait1Msec(1000);
	motor[left1]= b;
	motor[left2]= b;
	motor[right1]= b;
	motor[right2]= b;
	wait1Msec(3000);
	motor[up] = 75;
	motor[intake] = 75;
	wait1Msec(3000);
	motor[up] = 50;



}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	StopTask(autonomous);
	int powerExpanderBatteryV = SensorValue[in1]/.28;
	while(true)
	{

		int intakeControl = vexRT[Ch3];
		int driveLeftControl = vexRT[Ch3Xmtr2] * driveTrainSpeedControl;
		int driveRightControl = vexRT[Ch2Xmtr2] * driveTrainSpeedControl;
		int upControl = vexRT[Ch2];
		int startShooterControl = vexRT[Btn8D];
		int shooter30SpeedControl = vexRT[Btn6D];
		int shooter40SpeedControl = vexRT[Btn6U];
		int shooter43SpeedControl = vexRT[Btn7D];
		int shooter45SpeedControl = vexRT[Btn7L];
		int shooter47SpeedControl = vexRT[Btn7U];
		int shooter50SpeedControl = vexRT[Btn7R];
		int shooter55SpeedControl = vexRT[Btn5D];
		int shooter60SpeedControl = vexRT[Btn5U];
		int shooter35SpeedControl = vexRT[Btn8DXmtr2];
		int shooter37SpeedControl = vexRT[Btn8RXmtr2];

		//Drive Train Speed Control

		if(vexRT[Btn7DXmtr2] == 1)
		{
			driveTrainSpeedControl = 0.3;
		}
		else if(vexRT[Btn7UXmtr2] == 1)
		{
			driveTrainSpeedControl = 1;
		}


		// INTAKE
		if(abs(intakeControl) > deadzone)
		{
			motor[intake] = intakeControl;
			// control Intake
		}
		else
		{
			motor[intake] = 0;
			// stop Intake
		}
		//DRIVETRAIN LEFT
		if(abs(driveLeftControl) > deadzone)
		{
			motor[driveLeft] = driveLeftControl;
			motor[driveLeft2] = driveLeftControl;
		}
		else
		{
			motor[driveLeft] = 0;
			motor[driveLeft2] = 0;
		}
		//DRIVETRAIN RIGHT
		if(abs(driveRightControl) > deadzone)
		{
			motor[driveRight] = driveRightControl;
			motor[driveRight2] = driveRightControl;
		}
		else
		{
			motor[driveRight] = 0;
			motor[driveRight2] = 0;
		}
		//UP
		if(abs(upControl) > deadzone)
		{
			motor[up] = upControl;
			// start UP
		}
		else
		{
			motor[up] = 0;
			// stop UP
		}
		//START SHOOTER
		if(startShooterControl == 1)
		{
			motor[left1] = a;
			motor[left2] = a;
			motor[right1] = a;
			motor[right2] = a;
			wait1Msec(1000);
			motor[left1] = b * shootercorr;
			motor[left2] = b * shootercorr;
			motor[right1] = b * shootercorr;
			motor[right2] = b * shootercorr;
		}
		else if(vexRT[Btn8L] == 1)
		{

			motor[left1] = a;
			motor[left2] = a;
			motor[right1] = a;
			motor[right2] = a;
			wait1Msec(500);
			motor[left1] = a-5;
			motor[left2] = a-5;
			motor[right1] = a-5;
			motor[right2] = a-5;
			wait1Msec(500);
			motor[left1] = a-10;
			motor[left2] = a-10;
			motor[right1] = a-10;
			motor[right2] = a-10;
			wait1Msec(500);
			motor[left1] = a-15;
			motor[left2] = a-15;
			motor[right1] = a-15;
			motor[right2] = a-15;
			wait1Msec(500);
			motor[left1] = a-20;
			motor[left2] = a-20;
			motor[right1] = a-20;
			motor[right2] = a-20;
			wait1Msec(500);
			motor[left1] = a-30;
			motor[left2] = a-30;
			motor[right1] = a-30;
			motor[right2] = a-30;
			wait1Msec(500);
			motor[left1] = 0;
			motor[left2] = 0;
			motor[right1] = 0;
			motor[right2] = 0;
		}
		else if(shooter35SpeedControl == 1)
		{
			motor[left1] = 35*shootercorr;
			motor[left2] = 35*shootercorr;
			motor[right1] = 35*shootercorr;
			motor[right2] = 35*shootercorr;
		}
		else if(shooter37SpeedControl == 1)
		{
			motor[left1] = 37*shootercorr;
			motor[left2] = 37*shootercorr;
			motor[right1] = 37*shootercorr;
			motor[right2] = 37*shootercorr;
		}
		else if(shooter55SpeedControl == 1)
		{
			motor[left1] = 55*shootercorr;
			motor[left2] = 55*shootercorr;
			motor[right1] = 55*shootercorr;
			motor[right2] = 55*shootercorr;
		}
		else if(shooter30SpeedControl == 1)
		{
			motor[left1] = 30*shootercorr;
			motor[left2] = 30*shootercorr;
			motor[right1] = 30*shootercorr;
			motor[right2] = 30*shootercorr;
		}
		else if(shooter40SpeedControl == 1)
		{
			motor[left1] = 40*shootercorr;
			motor[left2] = 40*shootercorr;
			motor[right1] = 40*shootercorr;
			motor[right2] = 40*shootercorr;
		}
		else if(shooter50SpeedControl == 1)
		{
			motor[left1] = 50*shootercorr;
			motor[left2] = 50*shootercorr;
			motor[right1] = 50*shootercorr;
			motor[right2] = 50*shootercorr;
		}
		else if(shooter43SpeedControl == 1)
		{
			motor[left1] = 43*shootercorr;
			motor[left2] = 43*shootercorr;
			motor[right1] = 43*shootercorr;
			motor[right2] = 43*shootercorr;
		}
		else if(shooter47SpeedControl == 1)
		{
			motor[left1] = 47*shootercorr;
			motor[left2] = 47*shootercorr;
			motor[right1] = 47*shootercorr;
			motor[right2] = 47*shootercorr;
		}
		else if(shooter45SpeedControl == 1)
		{
			motor[left1] = 45*shootercorr;
			motor[left2] = 45*shootercorr;
			motor[right1] = 45*shootercorr;
			motor[right2] = 45*shootercorr;
		}
		else if(shooter60SpeedControl == 1)
		{
			motor[left1] = 60*shootercorr;
			motor[left2] = 60*shootercorr;
			motor[right1] = 60*shootercorr;
			motor[right2] = 60*shootercorr;
		}
		if(vexRT[Btn8U]) //* Emergency Stop *//
		{
			motor[left1] = 0;
			motor[left2] = 0;
			motor[right1] = 0;
			motor[right2] = 0;
		}

		//END CONTROLS

		/* ULTRASONIC READING */
		sonarValue = SensorValue(ultrasonic);



		if(vexRT[Btn8R] == 0)
		{
			// Displays Battery Levels to VEX Remote Screen
			powerExpanderBatteryV = SensorValue[in1]/.28;
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDPos(0,0);
			displayNextLCDString("Cortex Bat:");
			displayNextLCDNumber(nAvgBatteryLevel);
			displayLCDPos(1,0);
			displayNextLCDString("PowerE Bat:");
			displayNextLCDNumber(powerExpanderBatteryV);
		}
		else if(vexRT[Btn8R] == 1)
		{
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDPos(0,0);
			displayNextLCDString("Ultrasonic:");
			displayNextLCDNumber(sonarValue);
			displayLCDPos(1,0);
			displayNextLCDString("Exp. Bat");
			displayNextLCDNumber(powerExpanderBatteryV);
		}
	}
}
