#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    powerE,         sensorAnalog)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           up,            tmotorVex269, openLoop)
#pragma config(Motor,  port2,           left1,         tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           left2,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           driveLeft2,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           driveLeft,     tmotorVex393, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port6,           driveRight,    tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port7,           driveRight2,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           right1,        tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port9,           right2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          intake,        tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "SmartMotorLib.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
////////////////////////////////////////////////////////////////////////////////////////

	int a=50; // startup speed / slowdown speed
	int deadzone=15; // Deadzone for joysticks
	int b=65; // main shooting speed

	//vars for speed contorl
	int normalRPM = 47; //Speed in RPM when power is 60 (usually)
	int normalPower = 60; // Out of 127

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.


	SmartMotorsInit();
	SmartMotorsAddPowerExtender( left1, left2, right1, right2);
	SmartMotorLinkMotors( left1, left2);
	SmartMotorLinkMotors( right1, right2);
	SmartMotorPtcMonitorEnable();
	SmartMotorRun();

	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

		StopTask(usercontrol);
			SetMotor(left1, a);
			SetMotor(left2, a);
			SetMotor(right1, a);
			SetMotor(right2,a);
			SetMotor(left1, b);
			SetMotor(left2, b);
			SetMotor(right1, b);
			SetMotor(right2, b);
			wait1Msec(2000);
			SetMotor(up, 75);
			SetMotor(intake, 75);
			wait1Msec(3000);
			SetMotor(up, 50);



}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	StopTask(autonomous);
	while(true)
	{
	// CONTROLLER VARIABLES

		int intakeControl = vexRT[Ch3Xmtr2];
		int driveLeftControl = vexRT[Ch3];
		int driveRightControl = vexRT[Ch2];
		int upControl = vexRT[Ch2Xmtr2];
		int startShooterControl = vexRT[Btn8D];
		int shooter20SpeedControl = vexRT[Btn7D];
		int shooter30SpeedControl = vexRT[Btn7L];
		int shooter40SpeedControl = vexRT[Btn7U];
		int shooter50SpeedControl = vexRT[Btn7R];
		int shooter60SpeedControl = vexRT[Btn5U];
		int shooter70SpeedControl = vexRT[Btn5D];
		int shooter75SpeedControl = vexRT[Btn6U];
		int shooter80SpeedControl = vexRT[Btn6D];

		//Weird stuff for speed control

		int speedDropLeft = SmartMotorGetSpeed(left1) / normalRPM;
		int speedDropRight = SmartMotorGetSpeed(right1) / normalRPM;
		int increasedSpeedLeft = normalPower / speedDropLeft;
		int increasedSpeedRight = normalPower / speedDropRight;



	// INTAKE
		if(abs(intakeControl) > deadzone)
		{
			SetMotor(intake, intakeControl);
			// control Intake
		}
		else
		{
			SetMotor(intake, 0);
			// stop Intake
		}
		//DRIVETRAIN LEFT
		if(abs(driveLeftControl) > deadzone)
		{
			SetMotor(driveLeft, driveLeftControl);
			SetMotor(driveLeft2, driveLeftControl);
		}
		else
		{
			SetMotor(driveLeft, 0);
			SetMotor(driveLeft2, 0);
		}
		//DRIVETRAIN RIGHT
		if(abs(driveRightControl) > deadzone)
		{
			SetMotor(driveRight, driveRightControl);
			SetMotor(driveRight2, driveRightControl);
		}
		else
		{
			SetMotor(driveRight, 0);
			SetMotor(driveRight2, 0);
		}
		//UP
		if(abs(upControl) > deadzone)
		{
			SetMotor(up, upControl);
			// start UP
		}
		else
		{
			SetMotor(up, 0);
			// stop UP
		}
		//START SHOOTER
		if(startShooterControl == 1)
		{
			SetMotor(left1, a);
			SetMotor(left2, a);
			SetMotor(right1, a);
			SetMotor(right2, a);
			wait1Msec(1000);
			SetMotor(left1, increasedSpeedLeft);
			SetMotor(left2, increasedSpeedLeft);
			SetMotor(right1, increasedSpeedRight);
			SetMotor(right2, increasedSpeedRight);
		}
		else if(vexRT[Btn8L] == 1)
		{

			SetMotor(left1, a);
			SetMotor(left2, a);
			SetMotor(right1, a);
			SetMotor(right2, a);
			wait1Msec(500);
			SetMotor(left1, a-5);
			SetMotor(left2, a-5);
			SetMotor(right1, a-5);
			SetMotor(right2, a-5);
			wait1Msec(500);
			SetMotor(left1, a-10);
			SetMotor(left2, a-10);
			SetMotor(right1, a-10);
			SetMotor(right2, a-10);
			wait1Msec(500);
			SetMotor(left1, a-20);
			SetMotor(left2, a-20);
			SetMotor(right1, a-20);
			SetMotor(right2, a-20);
			wait1Msec(500);
			SetMotor(left1, a-30);
			SetMotor(left2, a-30);
			SetMotor(right1, a-30);
			SetMotor(right2, a-30);
			wait1Msec(500);
			SetMotor(left1, a-40);
			SetMotor(left2, a-40);
			SetMotor(right1, a-40);
			SetMotor(right2, a-40);
			wait1Msec(500);
			SetMotor(left1, 0);
			SetMotor(left2, 0);
			SetMotor(right1, 0);
			SetMotor(right2, 0);
		}
		else if(shooter20SpeedControl == 1)
		{
			SetMotor(left1, 20);
			SetMotor(left2, 20);
			SetMotor(right1, 20);
			SetMotor(right2, 20);
		}
		else if(shooter30SpeedControl == 1)
		{
			SetMotor(left1, 30);
			SetMotor(left2, 30);
			SetMotor(right1, 30);
			SetMotor(right2, 30);
		}
		else if(shooter40SpeedControl == 1)
		{
			SetMotor(left1, 40);
			SetMotor(left2, 40);
			SetMotor(right1, 40);
			SetMotor(right2, 40);
		}
		else if(shooter50SpeedControl == 1)
		{
			SetMotor(left1, 50);
			SetMotor(left2, 50);
			SetMotor(right1, 50);
			SetMotor(right2, 50);
		}
		else if(shooter60SpeedControl == 1)
		{
			SetMotor(left1, 60);
			SetMotor(left2, 60);
			SetMotor(right1, 60);
			SetMotor(right2, 60);
		}
		else if(shooter70SpeedControl == 1)
		{
			SetMotor(left1, 70);
			SetMotor(left2, 70);
			SetMotor(right1, 70);
			SetMotor(right2, 70);
		}
		else if(shooter75SpeedControl == 1)
		{
			SetMotor(left1, 75);
			SetMotor(left2, 75);
			SetMotor(right1, 75);
			SetMotor(right2, 75);
		}
		else if(shooter80SpeedControl == 1)
		{
			SetMotor(left1, 80);
			SetMotor(left2, 80);
			SetMotor(right1, 80);
			SetMotor(right2, 80);
		}
		if(vexRT[Btn8U]) //* Emergency Stop *//
		{
			SetMotor(left1, 0);
			SetMotor(left2, 0);
			SetMotor(right1, 0);
			SetMotor(right2, 0);
		}


		if(vexRT[Btn8R] == 0)
		{
			// Displays Battery Levels to VEX Remote Screen
			int powerExpanderBatteryV = SensorValue[in1]/.28;
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDPos(0,0);
			displayNextLCDString("Cortex Bat:");
			displayNextLCDNumber(nAvgBatteryLevel);
			displayLCDPos(1,0);
			displayNextLCDString("PowerE Bat:");
			displayNextLCDNumber(powerExpanderBatteryV);
		}
		else if(vexRT[Btn8R] == 1)
			{
					int leftTemp = SmartMotorGetTemperature(left1);
					int rightTemp = SmartMotorGetTemperature(right1);
					clearLCDLine(0);
					clearLCDLine(1);
					displayLCDPos(0,0);
					displayNextLCDString("LTempC:");
					displayNextLCDNumber(leftTemp);
					displayLCDPos(1,0);
					displayNextLCDString("RTempC:");
					displayNextLCDNumber(rightTemp);
			}
	}
}
