#pragma config(Sensor, in1,    powerE,         sensorAnalog)
#pragma config(Motor,  port2,           left1,         tmotorVex393, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           intake,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           driveLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           driveRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           up,            tmotorVex269, openLoop)
#pragma config(Motor,  port8,           right1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           right2,        tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int a=50; // startup speed / slowdown speed
	int deadzone=15; // Deadzone for joysticks
	int b=65; // main shooting speed
	int ddown = 60; //Shooting speed when 7D is pressed
	int dleft = 55; //Shooting speed 7L
	int dup = 50; //Shooting speed 7U
	int dright = 45; //Shooting speed 7R

	while(true)
	{
		//INTAKE
		if(abs(vexRT[Ch3Xmtr2]) > deadzone)
		{
			motor[intake] = vexRT[Ch3Xmtr2];  // stop Intake
		}
		else
		{
			motor[intake] = 0;  // start Intake
		}
		//DRIVETRAIN LEFT
		if(abs(vexRT[Ch3]) > deadzone)
		{
			motor[driveLeft] = vexRT[Ch3];
		}
		else
		{
			motor[driveLeft] = 0;
		}
		//DRIVETRAIN RIGHT
		if(abs(vexRT[Ch2]) > deadzone)
		{
			motor[driveRight] = vexRT[Ch2];
		}
		else
		{
			motor[driveRight] = 0;
		}
		//UP

		if(SensorBoolean[dgtl1] == 1 || SensorBoolean[dgtl2] == 1)
		{
			motor[up] = 0; //stop UP
			wait1Msec(250);
		}
		else if(abs(vexRT[Ch2Xmtr2]) > deadzone)
		{
			motor[up] = vexRT[Ch2Xmtr2] * 3/4 ;  // start UP
		}
		else
		{
			motor[up] = 0;  // stop UP
		}
		//START SHOOTER
		if(vexRT[Btn8D] == 1)
		{
			motor[left1] = a;
			motor[left2] = a;
			motor[right1] = a;
			motor[right2] = a;
			wait1Msec(1000);
			motor[left1] = b;
			motor[left2] = b;
			motor[right1] = b;
			motor[right2] = b;
		}
		else if(vexRT[Btn8L] == 1)
		{

			motor[left1] = a;
			motor[left2] = a;
			motor[right1] = a;
			motor[right2] = a;
			wait1Msec(500);
			motor[left1] = a-15;
			motor[left2] = a-15;
			motor[right1] = a-15;
			motor[right2] = a-15;
			wait1Msec(500);
			motor[left1] = a-30;
			motor[left2] = a-30;
			motor[right1] = a-30;
			motor[right2] = a-30;
			wait1Msec(500);
			motor[left1] = a-45;
			motor[left2] = a-45;
			motor[right1] = a-45;
			motor[right2] = a-45;
			wait1Msec(500);
			motor[left1] = 0;
			motor[left2] = 0;
			motor[right1] = 0;
			motor[right2] = 0;
		}
		else if(vexRT[Btn7D])
		{
			motor[left1] = ddown;
			motor[left2] = ddown;
			motor[right1] = ddown;
			motor[right2] = ddown;
		}
		else if(vexRT[Btn7L])
		{
			motor[left1] = dleft;
			motor[left2] = dleft;
			motor[right1] = dleft;
			motor[right2] = dleft;
		}
		else if(vexRT[Btn7U])
		{
			motor[left1] = dup;
			motor[left2] = dup;
			motor[right1] = dup;
			motor[right2] = dup;
		}
		else if(vexRT[Btn7R])
		{
			motor[left1] = dright;
			motor[left2] = dright;
			motor[right1] = dright;
			motor[right2] = dright;
		}
		else if(vexRT[Btn5U])
		{
			motor[left1] = 70;
			motor[left2] = 70;
			motor[right1] = 70;
			motor[right2] = 70;
		}
			else if(vexRT[Btn5L])
		{
			motor[left1] = 75;
			motor[left2] = 75;
			motor[right1] = 75;
			motor[right2] = 75;
		}
		if(vexRT[Btn8U])
		{
			motor[left1] = 0;
			motor[left2] = 0;
			motor[right1] = 0;
			motor[right2] = 0;
		}

			// Displays Battery Levels to VEX Remote Screen
			int powerExpanderBatteryV = SensorValue[in1]/.28;
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDPos(0,0);
			displayNextLCDString("Cortex Bat:");
			displayNextLCDNumber(nAvgBatteryLevel);
			displayLCDPos(1,0);
			displayNextLCDString("PowerE Bat:");
			displayNextLCDNumber(powerExpanderBatteryV);
	}
}
