#pragma config(Motor,  port1,           nonReversed,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          reversed,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//LEFT IS PORT 10, RIGHT IS PORT 1 (NON REVERSED)
task main()
{

	int x=100;

	wait1Msec(1000);
	motor[reversed]=x;
	motor[nonReversed]=x;
	wait1Msec(100000);

}
