#pragma config(Motor,  port2,           frontLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           intake,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           up,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           left1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           left2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           right1,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           right2,        tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int x=100; // intake speed
	int y=50;  // up speed
	int a=70; // shooting speed
	int deadzone=15;
	int negDeadZone=-15;
	int leftJoy = vexRT[Ch3]; // drivetrain left speed
	int rightJoy = vexRT[Ch2]; // drivetrain right speed

	wait1Msec(1000);

	while(true)
	{
		if(vexRT[Btn5D] == 1)
		{
			motor[intake] = 0;  // stop Intake
		}

		else if(vexRT[Btn5U] == 1)
		{
			motor[intake] = x;  // start Intake
		}
		else if(vexRT[Ch3] > deadzone) //
		{
			motor[frontLeft] = leftJoy;
		}
		else if(vexRT[Ch3] < negDeadZone)
		{
			motor[frontLeft] = -leftJoy;
		}
		else if(vexRT[Ch2] > deadzone)
		{
			motor[frontRight] = rightJoy;
		}
		else if(vexRT[Ch2] < negDeadZone)
		{
			motor[frontRight] = -rightJoy;
		}
		else if(vexRT[Ch3] < deadzone && vexRT[Ch3] > negDeadZone)
		{
			motor[frontLeft] = 0;
			motor[frontRight] = 0;
		}
		else if(vexRT[Ch2] > negDeadZone && vexRT[Ch2] < deadzone)
		{
			motor[frontLeft] = 0;
			motor[frontRight] = 0;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[up] = 0;  // stop up
		}

		else if(vexRT[Btn6U] == 1)
		{
			motor[up] = y;  // start up
		}
		else if(vexRT[Btn8D] == 1)
		{
			motor[left1] = a;
			motor[left2] = a;
			motor[right1] = a;
			motor[right2] = a;
		}
		else if(vexRT[Btn8L] == 1)
		{
			motor[left1] = 0;
			motor[left2] = 0;
			motor[right1] = 0;
			motor[right2] = 0;
		}
	}
}
